[versions]
# androidx
core-ktx = "1.10.0"
activity-compose = "1.7.1"
material3 = "1.1.0-rc01"
appcompat = "1.6.1"
annotation = "1.6.0"
librepass-client = "0.1.0-alpha8"
accompanist = "0.31.0-alpha"
material-icons-extended = "1.5.0-alpha03"
kotlinx-coroutines-android = "1.6.4"
navigation-compose = "2.5.3"
compose-bom = "2023.04.01"
room = "2.5.1"
compose-compiler = "1.4.6"

junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
# androidx
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
# room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# librepass client
librepass-client = { module = "dev.medzik.librepass:client", version.ref = "librepass-client" }

# com.google.accompanist
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# kotlin
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# debug
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

[plugins]

[bundles]
